name: CI/CD

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install 7-Zip
        run: |
          # Download 7-Zip
          curl -L -o 7z.exe https://www.7-zip.org/a/7z1900-x64.exe
          # Install 7-Zip silently
          Start-Process -FilePath ".\7z.exe" -ArgumentList "x -aoa" -Wait

      - name: Install Cocos Creator
        run: |
          # Download Cocos Creator
          curl -L -o cocos.zip https://download.cocos.com/CocosCreator/v3/CocosCreator_v3.6.2/CocosCreator_v3.6.2_Windows.zip
          # Extract Cocos Creator using 7-Zip
          .\7z.exe x -aoa cocos.zip -ococoscreator
          # Add Cocos Creator to the PATH
          echo "::add-path::$(PWD)/cocoscreator"

      - name: Build and Test
        run: |
          # Change to the project directory
          cd Cocos-ci-cd
          # Install project dependencies
          npm install
          # Build the project
          cocos compile -p web
          # Add any other build or test commands specific to your Cocos Creator project here
