name: CI/CD

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Cocos Creator
        run: |
          # Download Cocos Creator
          curl -L -o cocos.zip https://download.cocos.com/CocosCreator/v3/CocosCreator_v3.6.2/CocosCreator_v3.6.2_macOS.dmg
          # Extract Cocos Creator
          unzip -q cocos.zip
          # Rename extracted directory
          mv CocosCreator.app cocoscreator

      - name: Add Cocos Creator to PATH
        run: echo "::add-path::$(PWD)/cocoscreator"

      - name: Build and Test
        run: |
          # Change to the project directory
          cd Cocos-ci-cd
          # Install project dependencies
          npm install
          # Build the project
          cocos compile -p web
          # Add any other build or test commands specific to your Cocos Creator project here
